### ISSUE TITLE
Two things

### ISSUE THREAD

**Issue by jimmywarting** [darrachequesne/has-binary#6]
You are using `Buffer.isBuffer` to check if it's a `Buffer`... But buffer is also a instance of a `Uint8array` so maybe you could simplify this a bit by using `ArrayBuffer.isView(obj)` then we also get true for any other typed array which is also a binary
This also stop some compiler to import the buffer module b/c it sees that buffer is being used

the second thing is do you still need to use isArray? it exist natively `Array.isArray(obj)`

**Comment by darrachequesne** [comment]
Hi Jimmy! I think you are right, I implemented your suggested change here:
- buffer detection: https://github.com/darrachequesne/has-binary/commit/8bf8a81c696aa5a6ec14309b8fd67025cfa429cb
- isarray dependency: https://github.com/darrachequesne/has-binary/commit/76f1bb666fed0fd535144ab4b94c74dae50c2566

Released as `2.0.0`.
